#!/usr/bin/env python
# coding: utf-8

# In[4]:


import flask
import pickle
import pandas as pd

# Use pickle to load in the pre-trained model.
with open(f'model/price_model_4.pkl', 'rb') as f:
    model = pickle.load(f)
app = flask.Flask(__name__, template_folder='templates')

@app.route('/', methods=['GET', 'POST'])
def main():
    if flask.request.method == 'GET':
        return(flask.render_template('main.html'))
    if flask.request.method == 'POST':
        designer = flask.request.values['designer']
        size = flask.request.values['size']
        category = flask.request.values['category']
        image_count = flask.request.form['image_count']
        feedback_count = flask.request.form['feedback_count']
        condition = flask.request.values['condition']
    data = [[designer, size, condition, category, image_count,feedback_count,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0]]

    input_variables = pd.DataFrame(data, columns = ['designer', 'size', 'condition', 'category', 'image_count',
 'feedback_count',
 'condition_encoded',
 'product_class',
 'brand_value',
 'designer_(B).Stroy',
 'designer_.925 Silver Produced In Italy',
 'designer_032c',
 'designer_10 Deep',
 'designer_100 Thieves',
 'designer_1017 ALYX 9SM',
 'designer_10k Solid Gold',
 'designer_10sei0otto',
 'designer_11 By Boris Bidjan Saberi',
 'designer_14k Gold',
 'designer_14k Gold Chain',
 'designer_14k Gold Chain With Pendant',
 'designer_14k Gold Ring',
 'designer_18 East',
 'designer_18k Gold',
 'designer_20471120',
 'designer_21 Men',
 'designer_3.1 Phillip Lim',
 'designer_3si',
 'designer_3sixteen',
 'designer_3x1',
 "designer_40'S & Shorties",
 'designer_40oz NYC',
 'designer_424 On Fairfa',
 'designer_424 On Fairfax',
 'designer_45rpm',
 'designer_47',
 'designer_47 Brand',
 'designer_4x1111',
 'designer_5.11',
 'designer_50 Cent',
 'designer_5351 Pour Les Hommes',
 'designer_7 For All Mankind',
 'designer_88rising',
 'designer_925 Silver',
 'designer_99%Is',
 'designer_999 Club',
 'designer_A',
 'designer_A Cold Wall',
 "designer_A Day'S March",
 'designer_A Diciannoveventitre',
 'designer_A Kind Of Guise',
 'designer_A.P.C.',
 'designer_A1923',
 'designer_A24',
 'designer_AG Adriano Goldschmied',
 'designer_AMI',
 'designer_AWGE',
 'designer_Aaa',
 'designer_Aape',
 'designer_Abasi Rosborough',
 'designer_Abercrombie & Fitch',
 'designer_Absent',
 'designer_Absurd',
 'designer_Acapulco Gold',
 'designer_Acme Clothing',
 'designer_Acne Studios',
 'designer_Acronym',
 'designer_Adam Kimmel',
 'designer_Adaptation',
 'designer_Ader Error',
 'designer_Adidas',
 'designer_Adieu Paris',
 'designer_Adsum',
 'designer_Advisory Board Crystals',
 'designer_Advisry Clothing',
 'designer_Adyn',
 'designer_Aer',
 'designer_Aeropostale',
 'designer_Aether Apparel',
 'designer_Affix Works',
 'designer_Affliction',
 'designer_Agnes B.',
 'designer_Aime Leon Dore',
 'designer_Akila',
 'designer_Akings Ny',
 'designer_Akomplice',
 'designer_Albam',
 'designer_Alchemist',
 'designer_Alden',
 'designer_Aldo',
 'designer_Ale',
 'designer_Aleksandr Manamis',
 'designer_Alex Mill',
 'designer_Alexander Digenova',
 'designer_Alexander McQueen',
 'designer_Alexander Wang',
 'designer_Alexandre Plokhov',
 'designer_Alfani',
 'designer_Alfred Dunhill',
 'designer_Alien Workshop',
 'designer_Alife',
 'designer_All In',
 'designer_Allen Edmonds',
 'designer_Allsaints',
 'designer_Alltimers',
 'designer_Aloha Wear',
 'designer_Alpha Industries',
 'designer_Alpha Numeric Clothing',
 'designer_Alstyle',
 'designer_Altamont',
 'designer_Alternative Apparel',
 'designer_Aly',
 'designer_Alyx',
 'designer_Ambush Design',
 'designer_America',
 'designer_American Apparel',
 'designer_American Eagle Outfitters',
 'designer_American Giant',
 'designer_American Needle',
 'designer_American Rag',
 'designer_American Stitch',
 'designer_American Vintage',
 'designer_Amiri',
 'designer_Ammo Stilo',
 'designer_Analog',
 'designer_And Wander',
 'designer_Andersson Bell',
 'designer_Andrea Yaaqov',
 'designer_Andrew Marc',
 'designer_Andy Warhol',
 'designer_Ann Demeulemeester',
 'designer_Anonymous Ism',
 'designer_Anti Social Social Club',
 'designer_Antihero',
 'designer_Anvil',
 'designer_Anwar Carrots',
 'designer_Anything',
 'designer_Apathy',
 'designer_Apex One',
 'designer_Apolis',
 'designer_Apple',
 'designer_April 77',
 'designer_Aquascutum',
 "designer_Arc'Tery",
 "designer_Arc'Teryx",
 "designer_Arc'Teryx Veilance",
 'designer_Archival Clothing',
 'designer_Archivio J.M. Ribot',
 'designer_Aries',
 'designer_Aris Tatalovich',
 'designer_Arizona Jean Company',
 'designer_Armani',
 'designer_Armani Exchange',
 'designer_Army Of Me',
 'designer_Arpenteur',
 'designer_Art',
 'designer_Asap Rocky',
 'designer_Asics',
 'designer_Asket',
 'designer_Asos',
 'designer_Aspesi',
 'designer_Asspizza',
 'designer_Astrid Andersen',
 'designer_Atelier & Repairs',
 'designer_Atelier New Regime',
 'designer_Athletic',
 'designer_Atmos',
 'designer_Attachment',
 'designer_Auralee',
 'designer_Authentic',
 'designer_Avant Garde',
 'designer_Aviator Nation',
 'designer_Avirex',
 'designer_Awake',
 'designer_Axel Arigato',
 'designer_B.B. Simon',
 'designer_BV By Bodega',
 'designer_Babylon',
 'designer_Backpack',
 'designer_Bad',
 'designer_Balenciaga',
 'designer_Balmain',
 'designer_Band Tees',
 'designer_Bape',
 'designer_Barbour',
 'designer_Beams Plus',
 'designer_Bianca Chandon',
 'designer_Billionaire Boys Club',
 'designer_Boris Bidjan Saberi',
 'designer_Brain Dead',
 'designer_Brand',
 'designer_Burberry',
 'designer_Burberry Prorsum',
 'designer_C.P. Company',
 'designer_Call Me 917',
 'designer_Calvin Klein',
 'designer_Calvin Klein 205W39NYC',
 'designer_Camiel Fortgens',
 'designer_Camp High',
 'designer_Camper',
 'designer_Canada Goose',
 'designer_Canali',
 'designer_Canterbury Of New Zealand',
 'designer_Canvas',
 'designer_Carbon',
 'designer_Cardigan',
 'designer_Carhartt',
 'designer_Carhartt Wip',
 'designer_Carlo Colucci',
 'designer_Carmina',
 'designer_Carne Bollente',
 'designer_Carol Christian Poell',
 'designer_Carpe Diem',
 'designer_Carrots By Anwar',
 'designer_Cartier',
 'designer_Casablanca',
 'designer_Casey Casey',
 'designer_Casio',
 'designer_Caterpillar',
 'designer_Cav Empt',
 'designer_Cazal',
 'designer_Ccm',
 'designer_Celine',
 'designer_Chalk Line',
 'designer_Champion',
 'designer_Chance The Rapper',
 'designer_Chanel',
 'designer_Chaps',
 'designer_Chapter',
 'designer_Chase Authentics',
 'designer_Cheap Monday',
 'designer_Cherry LA',
 'designer_Chicago',
 'designer_Chimala',
 'designer_Chinatown Market',
 'designer_Chippewa',
 'designer_Christian Audigier',
 'designer_Christian Dior Monsieur',
 'designer_Christian Louboutin',
 'designer_Christopher Kane',
 'designer_Christopher Nemeth',
 'designer_Christos New York',
 'designer_Chrome Hearts',
 'designer_Chronicles Of Never',
 'designer_Chubbies',
 'designer_Churchs',
 'designer_Civil Regime',
 'designer_Clarks',
 'designer_Clear Weather',
 'designer_Cloak',
 'designer_Club Monaco',
 'designer_Cmmn Swdn',
 'designer_Coach',
 'designer_Coachella',
 'designer_Cold Laundry',
 'designer_Cole Buxton',
 'designer_Cole Haan',
 'designer_Colette',
 'designer_Colette Hyatt',
 'designer_Columbia',
 'designer_Come Tees',
 'designer_Comics',
 'designer_Comme Des Garcons',
 'designer_Common Projects',
 'designer_Converse',
 'designer_Coogi',
 'designer_Crocs',
 'designer_Cuban Link Chain',
 'designer_Custom',
 'designer_Custom Made',
 'designer_Custom Piece',
 'designer_Damir Doma',
 'designer_Designer',
 'designer_Diamond',
 'designer_Diamond Earrings',
 'designer_Diamond Supply Co',
 'designer_Dickies',
 'designer_Dior',
 'designer_Disney',
 'designer_Dolce & Gabbana',
 'designer_Dr. Martens',
 'designer_Dries Van Noten',
 'designer_Engineered Garments',
 'designer_Eric Emanuel',
 'designer_Fear Of God',
 'designer_Flatbush Zombies',
 'designer_Fragment Design',
 'designer_Frame',
 'designer_Frank Leder',
 'designer_Frank Ocean',
 'designer_Fred Perry',
 'designer_Freemans Sporting Club',
 'designer_Freenote',
 'designer_Freshjive',
 'designer_From The First',
 'designer_Frye',
 'designer_Fubu',
 'designer_Fuck The Population',
 'designer_Fucking Awesome',
 'designer_Fuct',
 'designer_Fugazi',
 'designer_Full Count & Co.',
 'designer_Full Send By Nelk Boys',
 'designer_Futura',
 'designer_Future',
 'designer_G Shock',
 'designer_G Star Raw',
 'designer_G Unit',
 'designer_G.H. Bass & Co.',
 'designer_G59 Records',
 'designer_Gallery Dept.',
 'designer_Ganryu',
 'designer_Gant',
 'designer_Gap',
 'designer_Garbstore',
 'designer_Garrett Leight',
 'designer_Gcds In Goal We Trust',
 'designer_General Research',
 'designer_Generic',
 'designer_Genius Pieces',
 'designer_Gentle Monster',
 'designer_Genuine Merchandise By True Fan',
 'designer_Geoffrey B. Small',
 'designer_George Co',
 'designer_Georrge Olivier',
 'designer_German',
 'designer_Gianni Mora',
 'designer_Gildan',
 'designer_Giorgio Armani',
 'designer_Girl Skateboards',
 'designer_Gitman Bros. Vintage',
 'designer_Giuseppe Zanotti',
 'designer_Givenchy',
 'designer_Glo Gang',
 'designer_GmbH',
 'designer_Gnarcotic',
 'designer_Gold',
 'designer_Gold Bracelet',
 'designer_Gold Chain',
 'designer_Gold Plated',
 'designer_Gold Ring',
 'designer_Golden Bear',
 'designer_Golden Goose',
 'designer_Golf Wang',
 'designer_Good Art',
 'designer_Good Music Merchandise',
 'designer_Goodenough',
 'designer_Goorin Bros.',
 'designer_Gosha Rubchinskiy',
 'designer_Goth Money',
 'designer_Grail',
 'designer_Gramicci',
 'designer_Grateful Dead',
 'designer_Greats',
 'designer_Greg Lauren',
 'designer_Grenson',
 'designer_Gstar',
 'designer_Guardian Angel',
 'designer_Gucci',
 'designer_Guerrilla Group',
 'designer_Guess',
 'designer_Guidi',
 'designer_Guns N Roses',
 'designer_Gustin',
 'designer_Gymshark',
 'designer_H&M',
 'designer_HIDDEN',
 'designer_Haider Ackermann',
 'designer_Half Evil',
 'designer_Han Kjobenhavn',
 'designer_Handmade',
 'designer_Hanes',
 'designer_Harder',
 'designer_HarlemBling',
 'designer_Harley Davidson',
 'designer_Harmony Paris',
 'designer_Harris Tweed',
 'designer_Have A Good Time',
 'designer_Haven',
 'designer_Head Porter',
 'designer_Helder Vices',
 'designer_Heliot Emil',
 'designer_Helly Hansen',
 'designer_Helmut Lang',
 'designer_Hender Scheme',
 'designer_Henrik Vibskov',
 'designer_Hermes',
 'designer_Herno',
 'designer_Heron Preston',
 'designer_Herschel Supply Co.',
 'designer_Hidden Characters',
 'designer_Highsnobiety',
 'designer_Hockey',
 'designer_Hockey Skateboards',
 'designer_Hoka One One',
 'designer_Holiday Brand',
 'designer_Hollister',
 'designer_Hollow Squad',
 'designer_Homme + Femme La',
 'designer_Honda',
 'designer_Honor The Gift',
 'designer_Hood By Air',
 'designer_Hook-Ups',
 'designer_Hope',
 'designer_Hot Mess',
 'designer_Howlin By Morrison',
 'designer_Hudson',
 'designer_Huf',
 'designer_Hugo Boss',
 'designer_Human Made',
 'designer_Hype',
 'designer_Hypebeast',
 'designer_Hysteric Glamour',
 'designer_Ian Connor',
 'designer_Iron Heart',
 'designer_Issey Miyake',
 'designer_J.Crew',
 'designer_Jordan Brand',
 'designer_Julius',
 'designer_Junya Watanabe',
 'designer_Just Cavalli',
 'designer_Justin Bieber',
 'designer_Kanye West',
 'designer_Kapital',
 'designer_Kaws',
 'designer_Kiko Kostadinov',
 'designer_Killion',
 'designer_Kiss',
 'designer_Kith',
 'designer_Kiton',
 'designer_Knickerbocker Mfg Co',
 'designer_Know Wave',
 'designer_Kodak',
 'designer_Kodone',
 'designer_Kody Phillips',
 'designer_Kokaine',
 'designer_Kollar Clothing',
 'designer_Kolor',
 'designer_Kris Van Assche',
 'designer_Ksubi',
 'designer_Kth Kill The Hype La',
 'designer_Ktz',
 'designer_Kuboraum',
 'designer_L.L. Bean',
 'designer_LIL PEEP',
 'designer_LRG',
 'designer_LVC',
 'designer_LaRopa',
 'designer_Label Under Construction',
 'designer_Lacoste',
 'designer_Lad Musician',
 'designer_Lady White Co.',
 'designer_Lakai',
 'designer_Lakers',
 'designer_Lancel',
 'designer_Lands End',
 'designer_Lanvin',
 'designer_Layer-0',
 'designer_Le Coq Sportif',
 'designer_Leather',
 'designer_Lee',
 'designer_Lego',
 'designer_Lemaire',
 'designer_Leon Emanuel Blanck',
 "designer_Levi'S",
 "designer_Levi'S Made & Crafted",
 'designer_Li Ning',
 'designer_Liam Hodges',
 'designer_Lifted Anchors',
 'designer_Lil Ugly Mane',
 'designer_Lil Uzi Vert',
 'designer_Lil Wayne',
 'designer_Lil Yachty',
 'designer_Liquid Blue',
 'designer_Local Authority',
 'designer_Loewe',
 'designer_Logic',
 'designer_Logo Athletic',
 'designer_Loro Piana',
 'designer_Los Angeles Dodgers',
 'designer_Lost & Found Ria Dunn',
 'designer_Louis Vuitton',
 'designer_Lqqk Studio',
 'designer_Lucchese',
 'designer_Lucky Brand',
 'designer_Luke Vicious',
 'designer_Lululemon',
 'designer_Lumen Et Umbra',
 'designer_Lumieres',
 'designer_Lxrdknows',
 'designer_Lyrical Lemonade',
 'designer_M+Rc Noir',
 'designer_MCM',
 'designer_MLB',
 'designer_MNML',
 'designer_MXDVS',
 'designer_Ma+',
 'designer_Mac Miller',
 'designer_Machus',
 'designer_Mackage',
 'designer_Mackintosh',
 'designer_MadeWorn',
 'designer_Madhappy',
 'designer_Maharishi',
 'designer_Maiden Noir',
 'designer_Maison Kitsune',
 'designer_Maison Margiela',
 'designer_Majestic',
 'designer_Marblesoda',
 'designer_Marc By Marc Jacobs',
 'designer_Marc Jacobs',
 'designer_Marcel Everette',
 'designer_Marcelo Burlon',
 'designer_Margaret Howell',
 'designer_Marine Layer',
 'designer_Marine Serre',
 'designer_Marino Infantry',
 'designer_Marino Morwood',
 'designer_Marithe Francois Girbaud',
 'designer_Mark Mcnairy New Amsterdam',
 'designer_Marlboro',
 'designer_Marmot',
 'designer_Marni',
 'designer_Marsell',
 'designer_Martine Ali',
 'designer_Martine Rose',
 'designer_Marvel Comics',
 'designer_Masnada',
 'designer_Massimo Dutti',
 'designer_MasterPiece',
 'designer_Mastermind Japan',
 'designer_Matsuda',
 'designer_Matthew Williamson',
 'designer_Medicom Bearbrick',
 'designer_Medicom Toy',
 'designer_Meermin',
 'designer_Mega Yacht',
 'designer_Members Only',
 'designer_Menace',
 'designer_Mercedes Benz',
 'designer_Merz B. Schwanen',
 'designer_Metallica',
 'designer_Mf Doom',
 'designer_Miansai',
 'designer_Michael Kors',
 'designer_Michiko Koshino',
 'designer_Mickey Mouse',
 'designer_Midnight Studios',
 'designer_Migos',
 'designer_Miharayasuhiro',
 'designer_Milfdad',
 'designer_Military',
 'designer_Mintcrew',
 'designer_Misbhv',
 'designer_Misc.',
 'designer_Misfits',
 'designer_Mishka',
 'designer_Mission Workshop',
 'designer_Missoni',
 'designer_Mister Freedom',
 'designer_Mitchell & Ness',
 'designer_Miu Miu',
 'designer_Mizuno',
 'designer_Mki Miyuki-Zoku',
 'designer_Modern Amusement',
 'designer_Moma',
 'designer_Momotaro',
 'designer_Moncler',
 'designer_Moncler Gamme Bleu',
 'designer_Mondaysuck',
 'designer_Monitaly',
 'designer_Montbell',
 'designer_Montblanc',
 'designer_Moose Knuckles',
 'designer_Moschino',
 'designer_Moscot',
 'designer_Mossimo',
 'designer_Mosthated',
 'designer_Mountain Hardwear',
 'designer_Mountain Research',
 'designer_Movie',
 'designer_Mr. Completely',
 'designer_Mr. P.',
 'designer_Msftsrep',
 'designer_Msgm',
 'designer_Muji',
 'designer_Mykita',
 'designer_N. Hoolywood',
 'designer_NBA',
 'designer_NFL',
 'designer_NHL',
 'designer_Naked & Famous',
 'designer_Namacheko',
 'designer_Nanamica',
 'designer_Nano Universe',
 'designer_Napapijri',
 'designer_Nas',
 'designer_Nasir Mazhar',
 'designer_Nautica',
 'designer_Ncaa',
 'designer_Necklace',
 'designer_Needles',
 'designer_Neff',
 'designer_Neighborhood',
 'designer_Neil Barrett',
 'designer_Neiman Marcus',
 'designer_Nemen',
 'designer_Nepenthes New York',
 'designer_New Balance',
 'designer_New Era',
 'designer_New Republic',
 'designer_New York Sunshine',
 'designer_Nickelodeon',
 'designer_Nigel Cabourn',
 'designer_Nike',
 'designer_Nike ACG',
 'designer_Nine Lives',
 'designer_Nintendo',
 'designer_Nirvana',
 'designer_Nissin',
 'designer_Nixon',
 'designer_Nn07',
 'designer_No Brand',
 'designer_No Name',
 'designer_No Vacancy Inn',
 'designer_Noah',
 'designer_Nom De Guerre',
 'designer_None',
 'designer_Nonnative',
 'designer_Noon Goons',
 'designer_Nordstrom',
 'designer_Norse Projects',
 'designer_Notorious Big',
 'designer_Nudie Jeans',
 'designer_Number (N)Ine',
 'designer_Nutmeg Mills',
 'designer_Oak NYC',
 'designer_Oak Street Bootmakers',
 'designer_Oakley',
 'designer_Oamc',
 'designer_Obama',
 'designer_Obey',
 'designer_Obscur',
 'designer_Octobers Very Own',
 'designer_Odd Future',
 'designer_Off-White',
 'designer_Officine Creative',
 'designer_Officine Generale',
 'designer_Ojardorf',
 'designer_Old Navy',
 'designer_Oliver Peoples',
 'designer_Oliver Spencer',
 'designer_One Piece',
 'designer_Oni',
 'designer_Onia',
 'designer_Online Ceramics',
 'designer_Only Ny',
 'designer_Opening Ceremony',
 'designer_Orbit Gear',
 'designer_Oree New York',
 'designer_Original Fake',
 'designer_Original Penguin',
 'designer_Orlebar Brown',
 'designer_Oro Los Angeles',
 'designer_Orslow',
 'designer_Orvis',
 'designer_Other',
 'designer_Other UK',
 'designer_Otto',
 'designer_Our Legacy',
 'designer_Outdoor Life',
 'designer_Outdoor Style Go Out!',
 'designer_Outdoor Voices',
 'designer_Outerknown',
 'designer_Outlier',
 'designer_Ovadia & Sons',
 'designer_PPFM',
 'designer_Paa',
 'designer_Pacsun',
 'designer_Paige',
 'designer_Palace',
 'designer_Palm Angels',
 'designer_Paraboot',
 'designer_Paradise',
 'designer_Parajumpers',
 'designer_Parra',
 'designer_Parts Of Four',
 'designer_Patagonia',
 'designer_Patrik Ervell',
 'designer_Patta',
 'designer_Paul Harnden Shoemakers',
 'designer_Paul Smith',
 'designer_Peaceminusone',
 'designer_Pelle Pelle',
 'designer_Pendleton',
 'designer_Penfield',
 'designer_Period Correct',
 'designer_Perks And Mini',
 'designer_Perry Ellis',
 'designer_Persol',
 'designer_Peter Millar',
 'designer_Pf Flyers',
 'designer_Pga Tour',
 'designer_Phenomenon',
 'designer_Philipp Plein',
 'designer_Pictureplane Alien Body',
 'designer_Pierre Balmain',
 'designer_Pierre Cardin',
 'designer_Pigalle',
 'designer_Pink Dolphin',
 'designer_Pink Floyd',
 'designer_Pizza Slime',
 'designer_Places + Faces',
 'designer_Play Cloths',
 'designer_Playboi Carti',
 'designer_Playboy',
 'designer_Pleasures',
 'designer_Poeme Bohemien',
 'designer_Pointer',
 'designer_Pokemon',
 'designer_Polar Skate Co.',
 'designer_Polaroid',
 'designer_Polo Ralph Lauren',
 'designer_Polythene* Optics',
 'designer_Porter',
 'designer_Portuguese Flannel',
 'designer_Post Archive Faction',
 'designer_Post Malone Tour Tee',
 'designer_Post Overalls',
 'designer_Pouya & $Uicideboy$ Merch',
 'designer_Prada',
 'designer_Premium Co.',
 'designer_Primitive',
 'designer_Prince',
 'designer_Private White V.C.',
 'designer_Pro Era',
 'designer_Profound Aesthetic',
 'designer_Prps',
 'designer_Psychworld',
 'designer_Public Housing Skate Team',
 'designer_Public School',
 'designer_Publish',
 'designer_Puma',
 'designer_Pure Blue Japan',
 'designer_Purple',
 'designer_Pyer Moss',
 'designer_Pyre',
 'designer_Pyrex Vision',
 'designer_Quartersnacks',
 'designer_Quicksilver',
 'designer_Quoddy',
 'designer_R.M. Williams',
 'designer_R13',
 'designer_READYMADE',
 'designer_ROA',
 'designer_ROSE IN GOOD FAITH',
 'designer_RRL Ralph Lauren',
 'designer_Raf Simons',
 'designer_Rag & Bone',
 'designer_Railcar Fine Goods',
 'designer_Rains',
 'designer_Raised By Wolves',
 'designer_Ralph Lauren',
 'designer_Ralph Lauren Black Label',
 'designer_Ralph Lauren Purple Label',
 'designer_Ralph Lauren Rugby',
 'designer_Random',
 'designer_Random Identities',
 'designer_Ransom Clothing',
 'designer_Rapha',
 'designer_Rare',
 'designer_Rare Panther',
 'designer_RayBan',
 'designer_Red Bull',
 'designer_Red Wing',
 'designer_Reebok',
 'designer_Reese Cooper',
 'designer_Rei',
 'designer_Reigning Champ',
 'designer_Reiss',
 'designer_Religion',
 'designer_Remi Relief',
 'designer_Represent Clo.',
 'designer_Resort Corps',
 'designer_Retrosuperfuture',
 'designer_Revenge',
 'designer_Revenge X Storm',
 'designer_Reyn Spooner',
 'designer_Rhude',
 'designer_Richardson',
 'designer_Richie Le Collection',
 'designer_Rick Owens',
 'designer_Rick Owens Drkshdw',
 'designer_Rimowa',
 'designer_Riot Division',
 'designer_Riot Society',
 'designer_Rip N Dip',
 'designer_Ripple Junction',
 'designer_River Island',
 'designer_Roark',
 'designer_Robert Geller',
 'designer_Robert Graham',
 'designer_Roberto Cavalli',
 'designer_Robins Jeans',
 'designer_Rocawear',
 'designer_Rock Revival',
 'designer_Rockers',
 'designer_Rogue Status',
 'designer_Rogue Territory',
 'designer_Rokit',
 'designer_Rolex',
 'designer_Ron Herman',
 'designer_Ronin Division',
 'designer_Ronning',
 'designer_Roots',
 'designer_Rosen',
 'designer_Rothco',
 'designer_Round Two',
 'designer_Rowing Blazers',
 'designer_Rrl',
 'designer_Rsvp Gallery',
 'designer_Rta',
 'designer_Rubber Keychain',
 'designer_S.N.S. Herning',
 'designer_Sacai',
 'designer_Sad Boys',
 'designer_Sage De Cret',
 'designer_Saint Laurent Paris',
 'designer_Saintwoods',
 'designer_Saks Fifth Avenue',
 'designer_Salem Sportswear',
 'designer_Salomon',
 'designer_Salvatore Ferragamo',
 'designer_Sample Industries',
 'designer_Samurai Jeans',
 'designer_Sandro',
 'designer_Santa Cruz',
 'designer_Santa Cruz Skateboards',
 'designer_Sasquatchfabrix',
 'designer_Sassafras',
 'designer_Satisfy',
 'designer_Saturdays New York City',
 'designer_Saturdays Surf Nyc',
 'designer_Saucony',
 'designer_Save Khaki',
 'designer_Schott',
 'designer_Sci-Fi Fantasy',
 'designer_Scotch & Soda',
 'designer_Sean John',
 'designer_Second/Layer',
 'designer_Section 8',
 'designer_Seiko',
 'designer_Seinfeld',
 'designer_Sergio Tacchini',
 'designer_Sesh',
 'designer_Seventh Heaven',
 'designer_Shadow Hill',
 'designer_Sheepskin Coat',
 'designer_Shockoe Atelier',
 'designer_Shoes Like Pottery',
 'designer_Siberia Hills',
 'designer_Sicko',
 'designer_Sies Marjan',
 'designer_Silent By Damir Doma',
 'designer_Silver',
 'designer_Simon Miller',
 'designer_Skoloct',
 'designer_Skulls',
 'designer_Slayer',
 'designer_Slipknot',
 'designer_Sneeze Magazine',
 'designer_Sniper Gang',
 'designer_Snoop Dogg',
 'designer_Snow Peak',
 'designer_Soccer Jersey',
 'designer_Solovair',
 'designer_Song For The Mute',
 'designer_Sony',
 'designer_Sophnet.',
 'designer_Sports Specialties',
 'designer_Sportswear',
 'designer_Starter',
 'designer_Sterling Silver',
 'designer_Stone Island',
 'designer_Street Fashion',
 'designer_Streetwear',
 'designer_Stussy',
 'designer_Superrradical',
 'designer_Supreme',
 'designer_The Hundreds',
 'designer_The North Face',
 'designer_The Weeknd',
 'designer_Thom Browne',
 'designer_Thrasher',
 'designer_Timberland',
 'designer_Tour Tee',
 'designer_Travis Scott',
 'designer_Umbro',
 'designer_Unbranded',
 'designer_Undefeated',
 'designer_Undercover',
 'designer_Uniqlo',
 'designer_Urban Outfitters',
 'designer_Valentino',
 'designer_Vans',
 'designer_Very Rare',
 'designer_Visvim',
 'designer_Vivienne Westwood',
 'designer_Vlone',
 'designer_Wacko Maria',
 'designer_Warren Lotas',
 'designer_Xbox 360',
 'designer_Yohji Yamamoto',
 'size_l',
 'size_m',
 'size_s',
 'size_xl',
 'size_xs',
 'size_xxl',
 'size_xxs',
 'category_group_bottoms',
 'category_group_footwear',
 'category_group_outerwear',
 'category_group_tailoring',
 'category_group_top'])
        #transform brand
    brand_list = ['Rubber Keychain',
 'Carbon',
 'Riot Society',
 'Pga Tour',
 'Aeropostale',
 'Ripple Junction',
 '.925 Silver Produced In Italy',
 'Rockers',
 'Gildan',
 'Onia',
 'Comics',
 'Nissin',
 'Chubbies',
 'Roark',
 '5.11',
 'Modern Amusement',
 'Ncaa',
 'Killion',
 'Sterling Silver',
 'Alstyle',
 'Necklace',
 '47 Brand',
 'Kodak',
 'Rothco',
 'Migos',
 'Polaroid',
 'Alfani',
 'Kokaine',
 'Obama',
 'Rei',
 '7 For All Mankind',
 'Nickelodeon',
 'American Eagle Outfitters',
 'Soccer Jersey',
 'Athletic',
 'Old Navy',
 '21 Men',
 'Absurd',
 'Generic',
 'Acapulco Gold',
 'Peter Millar',
 'Silver',
 'Alternative Apparel',
 'Acme Clothing',
 'Marine Layer',
 'Lego',
 'Goorin Bros.',
 'Publish',
 'Pokemon',
 'Play Cloths',
 'Milfdad',
 'Carne Bollente',
 'Urban Outfitters',
 'Misfits',
 'Lands End',
 'Prince',
 'Perry Ellis',
 'Logo Athletic',
 'MNML',
 'Genuine Merchandise By True Fan',
 'Chaps',
 'Original Penguin',
 'Lululemon',
 'Le Coq Sportif',
 'Canvas',
 'American Needle',
 'Notorious Big',
 'Gymshark',
 'Asos',
 'Polythene* Optics',
 'Armani Exchange',
 'Mondaysuck',
 '10 Deep',
 '47',
 'Arizona Jean Company',
 'Asket',
 'Xbox 360',
 'Pink Dolphin',
 'Pink Floyd',
 'Alltimers',
 'Aaa',
 "40'S & Shorties",
 'Lifted Anchors',
 'Rogue Status',
 'Thrasher',
 'Majestic',
 'Anwar Carrots',
 'Sneeze Magazine',
 'Obey',
 'American Stitch',
 'Have A Good Time',
 'Apex One',
 'Pf Flyers',
 'Outdoor Voices',
 'Diamond Supply Co',
 'Call Me 917',
 'Alex Mill',
 'Quicksilver',
 'Santa Cruz',
 'Chance The Rapper',
 'Hockey',
 'Post Malone Tour Tee',
 'Hockey Skateboards',
 'Rock Revival',
 '14k Gold Ring',
 'Only Ny',
 'Save Khaki',
 'Carlo Colucci',
 'Rocawear',
 'Uniqlo',
 'Kiss',
 'Outerknown',
 'American Apparel',
 'Nautica',
 'Liquid Blue',
 'Band Tees',
 'Maiden Noir',
 'Civil Regime',
 'Paige',
 'Cheap Monday',
 'Portuguese Flannel',
 'Muji',
 'Seinfeld',
 'Salem Sportswear',
 'Premium Co.',
 'Movie',
 'Machus',
 'American Rag',
 'Gant',
 'L.L. Bean',
 'Merz B. Schwanen',
 'Paa',
 'Slipknot',
 'Gustin',
 'NBA',
 'Shadow Hill',
 'Gnarcotic',
 'Lxrdknows',
 'NHL',
 'Chapter',
 'Gold Plated',
 'Saturdays Surf Nyc',
 'Sample Industries',
 'Santa Cruz Skateboards',
 'Aldo',
 'Know Wave',
 'Quartersnacks',
 'Saturdays New York City',
 'Lil Wayne',
 'River Island',
 'Reyn Spooner',
 'Profound Aesthetic',
 'MLB',
 'Logic',
 'Paradise',
 'Nutmeg Mills',
 'Rains',
 'NFL',
 'Custom Made',
 'Nudie Jeans',
 'Georrge Olivier',
 'Justin Bieber',
 'Luke Vicious',
 'Gap',
 '18k Gold',
 'Greats',
 'New Republic',
 'Gramicci',
 'Nn07',
 'Gitman Bros. Vintage',
 'Disney',
 'Nas',
 'America',
 'G Unit',
 'Ransom Clothing',
 'Sportswear',
 'Orvis',
 'Robert Graham',
 'Hudson',
 'Gold Ring',
 'Lil Ugly Mane',
 'RayBan',
 'Neff',
 'Pro Era',
 'BV By Bodega',
 'Good Music Merchandise',
 'Rare',
 'Lady White Co.',
 'Lil Yachty',
 'Cole Haan',
 'Tour Tee',
 'Future',
 'Mki Miyuki-Zoku',
 'Albam',
 'Mickey Mouse',
 'Nixon',
 'Hollister',
 'Reigning Champ',
 'Pouya & $Uicideboy$ Merch',
 'Unbranded',
 'Canterbury Of New Zealand',
 '40oz NYC',
 'Art',
 'Mountain Hardwear',
 'Members Only',
 'Abercrombie & Fitch',
 'Odd Future',
 'Public School',
 'Adyn',
 'Mercedes Benz',
 'Mintcrew',
 'Massimo Dutti',
 'Columbia',
 'Alife',
 'Mossimo',
 'AG Adriano Goldschmied',
 'Freshjive',
 'Gstar',
 'Scotch & Soda',
 'Miansai',
 'G Star Raw',
 'Antihero',
 'Knickerbocker Mfg Co',
 'Rokit',
 'Atelier New Regime',
 'Anonymous Ism',
 'Frame',
 'Alfred Dunhill',
 'Apathy',
 'Michiko Koshino',
 'Aquascutum',
 'Fubu',
 'Raised By Wolves',
 'Sergio Tacchini',
 'Hugo Boss',
 'Adsum',
 'Homme + Femme La',
 'Pleasures',
 'Umbro',
 'Ccm',
 'Rare Panther',
 'Pierre Cardin',
 'G.H. Bass & Co.',
 'Brand',
 '3x1',
 'Outdoor Life',
 'Han Kjobenhavn',
 'Chase Authentics',
 'Altamont',
 'Nintendo',
 'Herschel Supply Co.',
 'Half Evil',
 'Kollar Clothing',
 'Anything',
 'Highsnobiety',
 'Akila',
 'Ovadia & Sons',
 'Akomplice',
 'Saks Fifth Avenue',
 'Huf',
 'Rapha',
 'Richardson',
 'Naked & Famous',
 'Agnes B.',
 'Lucky Brand',
 '88rising',
 'One Piece',
 'Ralph Lauren Rugby',
 'Sniper Gang',
 'Street Fashion',
 'Hype',
 'Random',
 'Metallica',
 'Simon Miller',
 'Babylon',
 'Mishka',
 'Hope',
 'G59 Records',
 'No Name',
 'Outdoor Style Go Out!',
 'Perks And Mini',
 'A',
 'Club Monaco',
 'Awake',
 'Nano Universe',
 'Puma',
 'Christos New York',
 'Sesh',
 'Sony',
 'Helly Hansen',
 'Calvin Klein',
 'Affliction',
 'Marlboro',
 'Marblesoda',
 'Rsvp Gallery',
 'Carrots By Anwar',
 'Rag & Bone',
 'Custom Piece',
 'Slayer',
 'Fucking Awesome',
 'Guardian Angel',
 'Streetwear',
 'Montbell',
 'HIDDEN',
 'Remi Relief',
 'Otto',
 'Sci-Fi Fantasy',
 'April 77',
 'No Brand',
 "A Day'S March",
 'Honor The Gift',
 'Resort Corps',
 'Alien Workshop',
 'Polo Ralph Lauren',
 'Primitive',
 'Fuck The Population',
 'Diamond',
 'Lancel',
 'None',
 'Aape',
 'Skulls',
 'Hot Mess',
 'Other UK',
 'American Giant',
 'Snoop Dogg',
 'Penfield',
 'Mf Doom',
 'Allsaints',
 'Aloha Wear',
 'Garbstore',
 'Shockoe Atelier',
 'Aer',
 'American Vintage',
 'Pigalle',
 'Ronin Division',
 'Noon Goons',
 '925 Silver',
 'Shoes Like Pottery',
 'Christian Dior Monsieur',
 'Railcar Fine Goods',
 'All In',
 'Fred Perry',
 'Marino Infantry',
 'Mizuno',
 'Rowing Blazers',
 'Ralph Lauren',
 'Pizza Slime',
 'Misc.',
 'Public Housing Skate Team',
 'Polar Skate Co.',
 'Oak NYC',
 'Saucony',
 'Cardigan',
 'Lee',
 'Parra',
 'Christian Audigier',
 'Orbit Gear',
 'Marc By Marc Jacobs',
 'Religion',
 'Grateful Dead',
 'Noah',
 'Places + Faces',
 'Glo Gang',
 'Valentino',
 'Guess',
 'Msftsrep',
 'Prps',
 'Holiday Brand',
 'Hidden Characters',
 'Asap Rocky',
 'Sean John',
 'Mark Mcnairy New Amsterdam',
 'Backpack',
 'Hollow Squad',
 'Orlebar Brown',
 'Oliver Spencer',
 'Rip N Dip',
 'Aries',
 'Caterpillar',
 'Harley Davidson',
 '14k Gold Chain With Pendant',
 'Norse Projects',
 'Anvil',
 'Harder',
 'No Vacancy Inn',
 'Frye',
 'Silent By Damir Doma',
 'Come Tees',
 'Maison Kitsune',
 'Marvel Comics',
 'Kiko Kostadinov',
 '032c',
 'Post Overalls',
 'Mac Miller',
 'Riot Division',
 'Rolex',
 'Astrid Andersen',
 'Full Send By Nelk Boys',
 'Gold Bracelet',
 'Armani',
 'Andrew Marc',
 'Red Bull',
 'Nirvana',
 'Anti Social Social Club',
 'Superrradical',
 'Second/Layer',
 'Champion',
 'Christopher Kane',
 'Neiman Marcus',
 'Sasquatchfabrix',
 'Hypebeast',
 'Paul Smith',
 'Attachment',
 '14k Gold Chain',
 'Pointer',
 'HarlemBling',
 'Aviator Nation',
 'Military',
 'Freenote',
 'Roots',
 'Sage De Cret',
 'Allen Edmonds',
 '999 Club',
 'Chinatown Market',
 'Handmade',
 'Advisry Clothing',
 'Chippewa',
 'The Hundreds',
 'Atmos',
 'Local Authority',
 'Los Angeles Dodgers',
 'Designer',
 'Moschino',
 'H&M',
 'Playboy',
 'Michael Kors',
 'Lil Uzi Vert',
 '45rpm',
 'Custom',
 'Saintwoods',
 'Howlin By Morrison',
 'Fuct',
 'MXDVS',
 'Chicago',
 'Nike ACG',
 '3sixteen',
 'New Era',
 'Harmony Paris',
 'Mr. Completely',
 'Moma',
 'Chalk Line',
 'Goth Money',
 'Robert Geller',
 'Full Count & Co.',
 'Ronning',
 'Patagonia',
 'Harris Tweed',
 'Patrik Ervell',
 'Axel Arigato',
 'The Weeknd',
 'Dickies',
 'Just Cavalli',
 'Girl Skateboards',
 'Travis Scott',
 "Levi'S Made & Crafted",
 'Golf Wang',
 'Lyrical Lemonade',
 'Starter',
 'Section 8',
 'Pendleton',
 'Andrea Yaaqov',
 'PPFM',
 'Gold Chain',
 'Persol',
 'Casio',
 'Mosthated',
 'Satisfy',
 'Sophnet.',
 'Analog',
 'MadeWorn',
 'Apple',
 'Andy Warhol',
 'Affix Works',
 'Gianni Mora',
 'Lqqk Studio',
 'Lakers',
 'Freemans Sporting Club',
 'Lacoste',
 'Marithe Francois Girbaud',
 'Pelle Pelle',
 'Aspesi',
 'Undefeated',
 'Carhartt',
 'LVC',
 'Marcelo Burlon',
 '50 Cent',
 'Authentic',
 'Andersson Bell',
 'Head Porter',
 'Brain Dead',
 'Coogi',
 '5351 Pour Les Hommes',
 'Asspizza',
 'Army Of Me',
 'Nonnative',
 'Other',
 'Lad Musician',
 'Round Two',
 'Guns N Roses',
 'AWGE',
 'Helder Vices',
 'Pyre',
 'Rogue Territory',
 'Oro Los Angeles',
 'Marino Morwood',
 'Patta',
 'Quoddy',
 'Margaret Howell',
 'LaRopa',
 'Meermin',
 'Hanes',
 'Goodenough',
 'Psychworld',
 'Msgm',
 '14k Gold',
 '424 On Fairfax',
 'N. Hoolywood',
 'Lakai',
 'Ale',
 'Haven',
 'Porter',
 'Retrosuperfuture',
 'C.P. Company',
 'Clarks',
 'Beams Plus',
 'Adidas',
 'New York Sunshine',
 'Cmmn Swdn',
 'Period Correct',
 'Playboi Carti',
 'Ganryu',
 'Roberto Cavalli',
 'Represent Clo.',
 'Kodone',
 'Nepenthes New York',
 'Maharishi',
 'LIL PEEP',
 'J.Crew',
 'Purple',
 'Bianca Chandon',
 'Online Ceramics',
 "Levi'S",
 'Billionaire Boys Club',
 'Burberry Prorsum',
 'Diamond Earrings',
 'Sassafras',
 'Crocs',
 'Gosha Rubchinskiy',
 'Hysteric Glamour',
 'Grail',
 'Alpha Numeric Clothing',
 'Chronicles Of Never',
 'Cuban Link Chain',
 'Chimala',
 'Mr. P.',
 'Ksubi',
 'Flatbush Zombies',
 'Kth Kill The Hype La',
 'MasterPiece',
 'Gold',
 'Liam Hodges',
 'Palace',
 'Marmot',
 'Monitaly',
 'Kody Phillips',
 'Robins Jeans',
 'Lumieres',
 'S.N.S. Herning',
 'Very Rare',
 'Coachella',
 'Carhartt Wip',
 'Aether Apparel',
 '3.1 Phillip Lim',
 'Leather',
 'Alexander Wang',
 'Solovair',
 'Clear Weather',
 'Richie Le Collection',
 'Orslow',
 'Burberry',
 'Avant Garde',
 'Momotaro',
 'Adaptation',
 'Canali',
 'Skoloct',
 'Honda',
 'Kanye West',
 'Alpha Industries',
 'Colette Hyatt',
 'Reiss',
 'Midnight Studios',
 'Matsuda',
 'Cherry LA',
 'M+Rc Noir',
 '(+) People Jeans',
 'Acne Studios',
 'Henrik Vibskov',
 'Outlier',
 'Akings Ny',
 'Damir Doma',
 'The North Face',
 'Snow Peak',
 'Archival Clothing',
 'Genius Pieces',
 'Neil Barrett',
 'Atelier & Repairs',
 'Seventh Heaven',
 'Arpenteur',
 'Martine Ali',
 'A24',
 'Heron Preston',
 'Rosen',
 'A.P.C.',
 'Missoni',
 'Li Ning',
 'Montblanc',
 'Opening Ceremony',
 'Converse',
 'Christopher Nemeth',
 'Giorgio Armani',
 'Our Legacy',
 '424 On Fairfa',
 'Vans',
 'Neighborhood',
 '100 Thieves',
 'Pure Blue Japan',
 'Oakley',
 'Pierre Balmain',
 'Hood By Air',
 'Frank Leder',
 'Rrl',
 'Ammo Stilo',
 'Cole Buxton',
 'Nanamica',
 'Adam Kimmel',
 'Samurai Jeans',
 'Officine Generale',
 'Pacsun',
 'Garrett Leight',
 'Supreme',
 'Stussy',
 'Reebok',
 'Ktz',
 'Apolis',
 'Sports Specialties',
 'R13',
 'A Kind Of Guise',
 'Futura',
 'Mitchell & Ness',
 'Moscot',
 'Coach',
 'Yohji Yamamoto',
 'LRG',
 'Absent',
 'Marc Jacobs',
 'Lanvin',
 'Oni',
 "Arc'Teryx",
 'Ralph Lauren Black Label',
 'Oak Street Bootmakers',
 'RRL Ralph Lauren',
 'Kith',
 'Frank Ocean',
 'Grenson',
 'Revenge',
 'Alexander Digenova',
 'AMI',
 'Octobers Very Own',
 'Iron Heart',
 'Issey Miyake',
 'German',
 'Bad',
 'Nigel Cabourn',
 'Lost & Found Ria Dunn',
 'Barbour',
 'Kapital',
 '(B).Stroy',
 'Seiko',
 'Human Made',
 'Kolor',
 'Cloak',
 'Advisory Board Crystals',
 'ROSE IN GOOD FAITH',
 'General Research',
 'Menace',
 'Guerrilla Group',
 'Ader Error',
 'Gentle Monster',
 "Arc'Tery",
 'Cold Laundry',
 'Siberia Hills',
 '3si',
 'Gcds In Goal We Trust',
 'Mission Workshop',
 'G Shock',
 'Pyrex Vision',
 'Mega Yacht',
 'Red Wing',
 'Philipp Plein',
 'Poeme Bohemien',
 'Abasi Rosborough',
 'Auralee',
 'Kiton',
 '18 East',
 'A Cold Wall',
 'Comme Des Garcons',
 'Wacko Maria',
 'Salomon',
 'Number (N)Ine',
 'Rta',
 'Pictureplane Alien Body',
 'Oliver Peoples',
 'Salvatore Ferragamo',
 'Kris Van Assche',
 'Sad Boys',
 'Fear Of God',
 'Revenge X Storm',
 'Sicko',
 'Random Identities',
 'Nom De Guerre',
 'Reese Cooper',
 'Fragment Design',
 'Aime Leon Dore',
 'Lumen Et Umbra',
 'Madhappy',
 'Timberland',
 'Hook-Ups',
 'Original Fake',
 'Sandro',
 'Camp High',
 'Colette',
 'Helmut Lang',
 'Ian Connor',
 'Ralph Lauren Purple Label',
 'Oamc',
 'Alchemist',
 'Sies Marjan',
 'Aris Tatalovich',
 'Hoka One One',
 'Masnada',
 'Phenomenon',
 'Ambush Design',
 'Undercover',
 'Mountain Research',
 'Nasir Mazhar',
 'Cav Empt',
 'Vlone',
 'Misbhv',
 'Engineered Garments',
 'Bape',
 'Officine Creative',
 'Dolce & Gabbana',
 'Jordan Brand',
 'Giuseppe Zanotti',
 'Churchs',
 'Hermes',
 'Nike',
 'Cazal',
 'Marni',
 'Alexandre Plokhov',
 'R.M. Williams',
 'Ron Herman',
 'Sheepskin Coat',
 'Adieu Paris',
 'Eric Emanuel',
 'Asics',
 'Mykita',
 'Stone Island',
 'Balmain',
 'Nemen',
 'Nordstrom',
 'Golden Bear',
 'Medicom Toy',
 'Miu Miu',
 'Mister Freedom',
 'Golden Goose',
 '4x1111',
 'Mastermind Japan',
 'Obscur',
 'Warren Lotas',
 'Heliot Emil',
 'Herno',
 'MCM',
 'Chanel',
 'Off-White',
 'Needles',
 'Givenchy',
 'Napapijri',
 'Camiel Fortgens',
 'GmbH',
 'Common Projects',
 'Alexander McQueen',
 'New Balance',
 'Dries Van Noten',
 'Rhude',
 'Carmina',
 'Pyer Moss',
 'Camper',
 'Prada',
 'Aleksandr Manamis',
 'Marsell',
 'Marine Serre',
 'Lemaire',
 'And Wander',
 'Parajumpers',
 'Nine Lives',
 'Avirex',
 'Paraboot',
 'Song For The Mute',
 'Ojardorf',
 'Gucci',
 'Dr. Martens',
 'Lucchese',
 'Loro Piana',
 '10k Solid Gold',
 '11 By Boris Bidjan Saberi',
 'Junya Watanabe',
 'Parts Of Four',
 'Sacai',
 'Maison Margiela',
 'Marcel Everette',
 'Martine Rose',
 'Casey Casey',
 'Casablanca',
 'Oree New York',
 'Raf Simons',
 'Calvin Klein 205W39NYC',
 '10sei0otto',
 '20471120',
 'Aly',
 'ROA',
 'Hender Scheme',
 'Label Under Construction',
 'Palm Angels',
 'Kaws',
 'Julius',
 'Louis Vuitton',
 'Kuboraum',
 'Loewe',
 'Vivienne Westwood',
 'Alden',
 'B.B. Simon',
 'Ann Demeulemeester',
 'Matthew Williamson',
 'George Co',
 'Medicom Bearbrick',
 'Moncler',
 'Mackintosh',
 '1017 ALYX 9SM',
 'Good Art',
 'Miharayasuhiro',
 'Boris Bidjan Saberi',
 'From The First',
 'Haider Ackermann',
 'Thom Browne',
 'Namacheko',
 'Alyx',
 'Dior',
 'Private White V.C.',
 'Schott',
 'Peaceminusone',
 'Visvim',
 '99%Is',
 "Arc'Teryx Veilance",
 'Fugazi',
 'Moncler Gamme Bleu',
 'Saint Laurent Paris',
 'Balenciaga',
 'Rick Owens',
 'Gallery Dept.',
 'Cartier',
 'Carpe Diem',
 'Celine',
 'Chrome Hearts',
 'Canada Goose',
 'Geoffrey B. Small',
 'Rick Owens Drkshdw',
 'Ma+',
 'READYMADE',
 'Archivio J.M. Ribot',
 'Greg Lauren',
 'A Diciannoveventitre',
 'Post Archive Faction',
 'Christian Louboutin',
 'Leon Emanuel Blanck',
 'Mackage',
 'Moose Knuckles',
 'Amiri',
 'Acronym',
 'Layer-0',
 'Carol Christian Poell',
 'A1923',
 'Paul Harnden Shoemakers',
 'Rimowa',
 'Guidi']
    if input_variables['designer'].values in brand_list:
        brand_name = input_variables['designer'].values[0]
        brand_column = 'designer_'+ brand_name
        input_variables[brand_column] = 1
    else:
        input_variables['designer_Nike'] = 1
#transform size
    #Transform category
    top = ['Tank Tops & Sleeveless', 'Polos', 'Jerseys', 'Long Sleeve T-Shirts', 'Sweaters & Knitwear', 'Shirts (Button Ups)',
         'Sweatshirts & Hoodies', 'Short Sleeve T-Shirts']
    bottoms = ['Overalls & Jumpsuits','Swimwear', 'Cropped Pants', 'Shorts', 'Sweatpants & Joggers', 'Casual Pants', 'Denim']
    outerwear = ['Raincoats', 'Vests', 'Parkas', 'Denim Jackets', 'Leather Jackets', 'Heavy Coats', 'Bombers', 'Light Jackets']
    footwear = ['Sandals', 'Slip Ons', 'Formal Shoes','Casual Leather Shoes', 'Hi-Top Sneakers', 'Boots', 'Low-Top Sneakers']
    tailoring = ['Blazers']
    accessories = ['Ties & Pocketsquares', 'Periodicals', 'Glasses', 'Socks & Underwear', 'Gloves & Scarves','Wallets', 'Belts', 'Sunglasses', 'Bags & Luggage',
                'Miscellaneous', 'Jewelry & Watches', 'Hats']

    cat_name = input_variables['category'].values[0]
    if cat_name in bottoms:
        input_variables['category_group_bottoms'] = 1
        input_variables['category_group'] = 'bottoms'
    elif cat_name in top:
        input_variables['category_group_top'] = 1
        input_variables['category_group'] = 'top'
    elif cat_name in outerwear:
        input_variables['category_group_outerwear'] = 1
        input_variables['category_group'] = 'outerwear'
    elif cat_name in footwear:
        input_variables['category_group_footwear'] = 1
        input_variables['category_group'] = 'footwear'
    elif cat_name in tailoring:
        input_variables['category_group_tailoring'] = 1
        input_variables['category_group'] = 'tailoring'
    else:
        input_variables['category_group_top'] = 1
        input_variables['category_group'] = 'top'
    input_variables.drop(columns = ['category'], inplace = True)
    # transform condition
    if input_variables["condition"].values[0] in ['Gently used', 'New', 'Used', 'Worn']:
        input_variables["condition_encoded"] = input_variables.condition.astype("category")
        input_variables["condition_encoded"] = input_variables["condition_encoded"].replace(['Gently used', 'New', 'Used', 'Worn'], [1, 0, 2, 3])
        input_variables["condition_encoded"]
    else:
        input_variables["condition_encoded"] = input_variables.condition.astype("category")
        input_variables["condition_encoded"] = 2
    input_variables.drop(columns = ['condition'], inplace = True)


    brand_0 = ['Rubber Keychain',
 'Carbon',
 'Riot Society',
 'Pga Tour',
 'Aeropostale',
 'Ripple Junction',
 '.925 Silver Produced In Italy',
 'Rockers',
 'Gildan',
 'Onia',
 'Comics',
 'Nissin',
 'Chubbies',
 'Roark',
 '5.11',
 'Modern Amusement',
 'Ncaa',
 'Killion',
 'Sterling Silver',
 'Alstyle',
 'Necklace',
 '47 Brand',
 'Kodak',
 'Rothco',
 'Migos',
 'Polaroid',
 'Alfani',
 'Kokaine',
 'Obama',
 'Rei',
 '7 For All Mankind',
 'Nickelodeon',
 'American Eagle Outfitters',
 'Soccer Jersey',
 'Athletic',
 'Old Navy',
 '21 Men',
 'Absurd',
 'Generic',
 'Acapulco Gold',
 'Peter Millar',
 'Silver',
 'Alternative Apparel',
 'Acme Clothing',
 'Marine Layer',
 'Lego',
 'Goorin Bros.',
 'Publish',
 'Pokemon',
 'Play Cloths',
 'Milfdad',
 'Carne Bollente',
 'Urban Outfitters',
 'Misfits',
 'Lands End',
 'Prince',
 'Perry Ellis',
 'Logo Athletic',
 'MNML',
 'Genuine Merchandise By True Fan',
 'Chaps',
 'Original Penguin',
 'Lululemon',
 'Le Coq Sportif',
 'Canvas',
 'American Needle',
 'Notorious Big',
 'Gymshark',
 'Asos',
 'Polythene* Optics',
 'Armani Exchange',
 'Mondaysuck',
 '10 Deep',
 '47',
 'Arizona Jean Company',
 'Asket',
 'Xbox 360',
 'Pink Dolphin',
 'Pink Floyd',
 'Alltimers',
 'Aaa',
 "40'S & Shorties",
 'Lifted Anchors',
 'Rogue Status',
 'Thrasher',
 'Majestic',
 'Anwar Carrots',
 'Sneeze Magazine',
 'Obey',
 'American Stitch',
 'Have A Good Time',
 'Apex One',
 'Pf Flyers',
 'Outdoor Voices',
 'Diamond Supply Co',
 'Call Me 917',
 'Alex Mill',
 'Quicksilver',
 'Santa Cruz',
 'Chance The Rapper',
 'Hockey',
 'Post Malone Tour Tee',
 'Hockey Skateboards',
 'Rock Revival',
 '14k Gold Ring',
 'Only Ny',
 'Save Khaki',
 'Carlo Colucci',
 'Rocawear',
 'Uniqlo',
 'Kiss',
 'Outerknown',
 'American Apparel',
 'Nautica',
 'Liquid Blue',
 'Band Tees',
 'Maiden Noir',
 'Civil Regime',
 'Paige',
 'Cheap Monday',
 'Portuguese Flannel',
 'Muji',
 'Seinfeld',
 'Salem Sportswear',
 'Premium Co.',
 'Movie',
 'Machus',
 'American Rag',
 'Gant',
 'L.L. Bean',
 'Merz B. Schwanen',
 'Paa',
 'Slipknot',
 'Gustin',
 'NBA',
 'Shadow Hill',
 'Gnarcotic',
 'Lxrdknows',
 'NHL',
 'Chapter',
 'Gold Plated',
 'Saturdays Surf Nyc',
 'Sample Industries',
 'Santa Cruz Skateboards',
 'Aldo',
 'Know Wave',
 'Quartersnacks',
 'Saturdays New York City',
 'Lil Wayne',
 'River Island',
 'Reyn Spooner',
 'Profound Aesthetic',
 'MLB',
 'Logic',
 'Paradise',
 'Nutmeg Mills',
 'Rains',
 'NFL',
 'Custom Made',
 'Nudie Jeans',
 'Georrge Olivier',
 'Justin Bieber',
 'Luke Vicious',
 'Gap',
 '18k Gold',
 'Greats',
 'New Republic',
 'Gramicci',
 'Nn07',
 'Gitman Bros. Vintage',
 'Disney',
 'Nas',
 'America',
 'G Unit',
 'Ransom Clothing',
 'Sportswear',
 'Orvis',
 'Robert Graham',
 'Hudson',
 'Gold Ring',
 'Lil Ugly Mane',
 'RayBan',
 'Neff',
 'Pro Era',
 'BV By Bodega',
 'Good Music Merchandise',
 'Rare',
 'Lady White Co.',
 'Lil Yachty',
 'Cole Haan',
 'Tour Tee',
 'Future',
 'Mki Miyuki-Zoku',
 'Albam',
 'Mickey Mouse',
 'Nixon',
 'Hollister',
 'Reigning Champ',
 'Pouya & $Uicideboy$ Merch',
 'Unbranded',
 'Canterbury Of New Zealand',
 '40oz NYC',
 'Art',
 'Mountain Hardwear',
 'Members Only',
 'Abercrombie & Fitch',
 'Odd Future',
 'Public School',
 'Adyn',
 'Mercedes Benz',
 'Mintcrew',
 'Massimo Dutti',
 'Columbia',
 'Alife',
 'Mossimo',
 'AG Adriano Goldschmied',
 'Freshjive',
 'Gstar',
 'Scotch & Soda',
 'Miansai',
 'G Star Raw',
 'Antihero',
 'Knickerbocker Mfg Co',
 'Rokit',
 'Atelier New Regime',
 'Anonymous Ism']
    brand_1 = ['Frame',
 'Alfred Dunhill',
 'Apathy',
 'Michiko Koshino',
 'Aquascutum',
 'Fubu',
 'Raised By Wolves',
 'Sergio Tacchini',
 'Hugo Boss',
 'Adsum',
 'Homme + Femme La',
 'Pleasures',
 'Umbro',
 'Ccm',
 'Rare Panther',
 'Pierre Cardin',
 'G.H. Bass & Co.',
 'Brand',
 '3x1',
 'Outdoor Life',
 'Han Kjobenhavn',
 'Chase Authentics',
 'Altamont',
 'Nintendo',
 'Herschel Supply Co.',
 'Half Evil',
 'Kollar Clothing',
 'Anything',
 'Highsnobiety',
 'Akila',
 'Ovadia & Sons',
 'Akomplice',
 'Saks Fifth Avenue',
 'Huf',
 'Rapha',
 'Richardson',
 'Naked & Famous',
 'Agnes B.',
 'Lucky Brand',
 '88rising',
 'One Piece',
 'Ralph Lauren Rugby',
 'Sniper Gang',
 'Street Fashion',
 'Hype',
 'Random',
 'Metallica',
 'Simon Miller',
 'Babylon',
 'Mishka',
 'Hope',
 'G59 Records',
 'No Name',
 'Outdoor Style Go Out!',
 'Perks And Mini',
 'A',
 'Club Monaco',
 'Awake',
 'Nano Universe',
 'Puma',
 'Christos New York',
 'Sesh',
 'Sony',
 'Helly Hansen',
 'Calvin Klein',
 'Affliction',
 'Marlboro',
 'Marblesoda',
 'Rsvp Gallery',
 'Carrots By Anwar',
 'Rag & Bone',
 'Custom Piece',
 'Slayer',
 'Fucking Awesome',
 'Guardian Angel',
 'Streetwear',
 'Montbell',
 'HIDDEN',
 'Remi Relief',
 'Otto',
 'Sci-Fi Fantasy',
 'April 77',
 'No Brand',
 "A Day'S March",
 'Honor The Gift',
 'Resort Corps',
 'Alien Workshop',
 'Polo Ralph Lauren',
 'Primitive',
 'Fuck The Population',
 'Diamond',
 'Lancel',
 'None',
 'Aape',
 'Skulls',
 'Hot Mess',
 'Other UK',
 'American Giant',
 'Snoop Dogg',
 'Penfield',
 'Mf Doom',
 'Allsaints',
 'Aloha Wear',
 'Garbstore',
 'Shockoe Atelier',
 'Aer',
 'American Vintage',
 'Pigalle',
 'Ronin Division',
 'Noon Goons',
 '925 Silver',
 'Shoes Like Pottery',
 'Christian Dior Monsieur',
 'Railcar Fine Goods',
 'All In',
 'Fred Perry',
 'Marino Infantry',
 'Mizuno',
 'Rowing Blazers',
 'Ralph Lauren',
 'Pizza Slime',
 'Misc.',
 'Public Housing Skate Team',
 'Polar Skate Co.',
 'Oak NYC',
 'Saucony',
 'Cardigan',
 'Lee',
 'Parra',
 'Christian Audigier',
 'Orbit Gear',
 'Marc By Marc Jacobs',
 'Religion',
 'Grateful Dead',
 'Noah',
 'Places + Faces',
 'Glo Gang',
 'Valentino',
 'Guess',
 'Msftsrep',
 'Prps',
 'Holiday Brand',
 'Hidden Characters',
 'Asap Rocky',
 'Sean John',
 'Mark Mcnairy New Amsterdam',
 'Backpack',
 'Hollow Squad',
 'Orlebar Brown',
 'Oliver Spencer',
 'Rip N Dip',
 'Aries',
 'Caterpillar',
 'Harley Davidson',
 '14k Gold Chain With Pendant',
 'Norse Projects',
 'Anvil',
 'Harder',
 'No Vacancy Inn',
 'Frye',
 'Silent By Damir Doma',
 'Come Tees',
 'Maison Kitsune',
 'Marvel Comics',
 'Kiko Kostadinov',
 '032c',
 'Post Overalls',
 'Mac Miller',
 'Riot Division',
 'Rolex',
 'Astrid Andersen',
 'Full Send By Nelk Boys',
 'Gold Bracelet',
 'Armani',
 'Andrew Marc',
 'Red Bull',
 'Nirvana',
 'Anti Social Social Club',
 'Superrradical',
 'Second/Layer',
 'Champion',
 'Christopher Kane',
 'Neiman Marcus',
 'Sasquatchfabrix',
 'Hypebeast',
 'Paul Smith',
 'Attachment',
 '14k Gold Chain',
 'Pointer',
 'HarlemBling',
 'Aviator Nation',
 'Military',
 'Freenote',
 'Roots',
 'Sage De Cret',
 'Allen Edmonds',
 '999 Club',
 'Chinatown Market',
 'Handmade',
 'Advisry Clothing',
 'Chippewa',
 'The Hundreds',
 'Atmos',
 'Local Authority',
 'Los Angeles Dodgers',
 'Designer',
 'Moschino',
 'H&M',
 'Playboy',
 'Michael Kors',
 'Lil Uzi Vert',
 '45rpm',
 'Custom',
 'Saintwoods',
 'Howlin By Morrison',
 'Fuct',
 'MXDVS',
 'Chicago',
 'Nike ACG',
 '3sixteen',
 'New Era',
 'Harmony Paris',
 'Mr. Completely',
 'Moma',
 'Chalk Line',
 'Goth Money']
    brand_2 = ['Robert Geller',
 'Full Count & Co.',
 'Ronning',
 'Patagonia',
 'Harris Tweed',
 'Patrik Ervell',
 'Axel Arigato',
 'The Weeknd',
 'Dickies',
 'Just Cavalli',
 'Girl Skateboards',
 'Travis Scott',
 "Levi'S Made & Crafted",
 'Golf Wang',
 'Lyrical Lemonade',
 'Starter',
 'Section 8',
 'Pendleton',
 'Andrea Yaaqov',
 'PPFM',
 'Gold Chain',
 'Persol',
 'Casio',
 'Mosthated',
 'Satisfy',
 'Sophnet.',
 'Analog',
 'MadeWorn',
 'Apple',
 'Andy Warhol',
 'Affix Works',
 'Gianni Mora',
 'Lqqk Studio',
 'Lakers',
 'Freemans Sporting Club',
 'Lacoste',
 'Marithe Francois Girbaud',
 'Pelle Pelle',
 'Aspesi',
 'Undefeated',
 'Carhartt',
 'LVC',
 'Marcelo Burlon',
 '50 Cent',
 'Authentic',
 'Andersson Bell',
 'Head Porter',
 'Brain Dead',
 'Coogi',
 '5351 Pour Les Hommes',
 'Asspizza',
 'Army Of Me',
 'Nonnative',
 'Other',
 'Lad Musician',
 'Round Two',
 'Guns N Roses',
 'AWGE',
 'Helder Vices',
 'Pyre',
 'Rogue Territory',
 'Oro Los Angeles',
 'Marino Morwood',
 'Patta',
 'Quoddy',
 'Margaret Howell',
 'LaRopa',
 'Meermin',
 'Hanes',
 'Goodenough',
 'Psychworld',
 'Msgm',
 '14k Gold',
 '424 On Fairfax',
 'N. Hoolywood',
 'Lakai',
 'Ale',
 'Haven',
 'Porter',
 'Retrosuperfuture',
 'C.P. Company',
 'Clarks',
 'Beams Plus',
 'Adidas',
 'New York Sunshine',
 'Cmmn Swdn',
 'Period Correct',
 'Playboi Carti',
 'Ganryu',
 'Roberto Cavalli',
 'Represent Clo.',
 'Kodone',
 'Nepenthes New York',
 'Maharishi',
 'LIL PEEP',
 'J.Crew',
 'Purple',
 'Bianca Chandon',
 'Online Ceramics',
 "Levi'S",
 'Billionaire Boys Club',
 'Burberry Prorsum',
 'Diamond Earrings',
 'Sassafras',
 'Crocs',
 'Gosha Rubchinskiy',
 'Hysteric Glamour',
 'Grail',
 'Alpha Numeric Clothing',
 'Chronicles Of Never',
 'Cuban Link Chain',
 'Chimala',
 'Mr. P.',
 'Ksubi',
 'Flatbush Zombies',
 'Kth Kill The Hype La',
 'MasterPiece',
 'Gold',
 'Liam Hodges',
 'Palace',
 'Marmot',
 'Monitaly',
 'Kody Phillips',
 'Robins Jeans',
 'Lumieres',
 'S.N.S. Herning',
 'Very Rare',
 'Coachella',
 'Carhartt Wip',
 'Aether Apparel',
 '3.1 Phillip Lim',
 'Leather',
 'Alexander Wang',
 'Solovair',
 'Clear Weather',
 'Richie Le Collection',
 'Orslow',
 'Burberry',
 'Avant Garde',
 'Momotaro',
 'Adaptation',
 'Canali',
 'Skoloct',
 'Honda',
 'Kanye West',
 'Alpha Industries',
 'Colette Hyatt',
 'Reiss',
 'Midnight Studios',
 'Matsuda',
 'Cherry LA',
 'M+Rc Noir',
 '(+) People Jeans',
 'Acne Studios',
 'Henrik Vibskov',
 'Outlier',
 'Akings Ny',
 'Damir Doma',
 'The North Face',
 'Snow Peak',
 'Archival Clothing',
 'Genius Pieces',
 'Neil Barrett',
 'Atelier & Repairs',
 'Seventh Heaven',
 'Arpenteur',
 'Martine Ali',
 'A24',
 'Heron Preston',
 'Rosen',
 'A.P.C.',
 'Missoni',
 'Li Ning',
 'Montblanc',
 'Opening Ceremony',
 'Converse',
 'Christopher Nemeth',
 'Giorgio Armani',
 'Our Legacy',
 '424 On Fairfa',
 'Vans',
 'Neighborhood',
 '100 Thieves',
 'Pure Blue Japan',
 'Oakley',
 'Pierre Balmain',
 'Hood By Air',
 'Frank Leder',
 'Rrl',
 'Ammo Stilo',
 'Cole Buxton',
 'Nanamica',
 'Adam Kimmel',
 'Samurai Jeans',
 'Officine Generale',
 'Pacsun',
 'Garrett Leight',
 'Supreme',
 'Stussy',
 'Reebok',
 'Ktz',
 'Apolis',
 'Sports Specialties',
 'R13',
 'A Kind Of Guise',
 'Futura',
 'Mitchell & Ness',
 'Moscot',
 'Coach',
 'LRG',
 'Absent',
 'Marc Jacobs',
 'Lanvin',
 'Oni',
 "Arc'Teryx",
 'Ralph Lauren Black Label',
 'Oak Street Bootmakers',
 'RRL Ralph Lauren',
 'Kith',
 'Frank Ocean',
 'Grenson',
 'Revenge',
 'Alexander Digenova',
 'AMI',
 'Octobers Very Own',
  'Asics',
  'Nike',
  'Barbour',
   'New Balance']
    brand_3 = ['Iron Heart',
 'Issey Miyake',
 'Yohji Yamamoto',
 'German',
 'Bad',
 'Nigel Cabourn',
 'Lost & Found Ria Dunn',
 'Kapital',
 '(B).Stroy',
 'Seiko',
 'Human Made',
 'Kolor',
 'Cloak',
 'Advisory Board Crystals',
 'ROSE IN GOOD FAITH',
 'General Research',
 'Menace',
 'Guerrilla Group',
 'Ader Error',
 'Gentle Monster',
 "Arc'Tery",
 'Cold Laundry',
 'Siberia Hills',
 '3si',
 'Gcds In Goal We Trust',
 'Mission Workshop',
 'G Shock',
 'Pyrex Vision',
 'Mega Yacht',
 'Red Wing',
 'Philipp Plein',
 'Poeme Bohemien',
 'Abasi Rosborough',
 'Auralee',
 'Kiton',
 '18 East',
 'A Cold Wall',
 'Comme Des Garcons',
 'Wacko Maria',
 'Salomon',
 'Number (N)Ine',
 'Rta',
 'Pictureplane Alien Body',
 'Oliver Peoples',
 'Salvatore Ferragamo',
 'Kris Van Assche',
 'Sad Boys',
 'Fear Of God',
 'Revenge X Storm',
 'Sicko',
 'Random Identities',
 'Nom De Guerre',
 'Reese Cooper',
 'Fragment Design',
 'Aime Leon Dore',
 'Lumen Et Umbra',
 'Madhappy',
 'Timberland',
 'Hook-Ups',
 'Original Fake',
 'Sandro',
 'Camp High',
 'Colette',
 'Helmut Lang',
 'Ian Connor',
 'Ralph Lauren Purple Label',
 'Oamc',
 'Alchemist',
 'Sies Marjan',
 'Aris Tatalovich',
 'Hoka One One',
 'Masnada',
 'Phenomenon',
 'Ambush Design',
 'Undercover',
 'Mountain Research',
 'Nasir Mazhar',
 'Cav Empt',
 'Vlone',
 'Misbhv',
 'Engineered Garments',
 'Bape',
 'Officine Creative',
 'Dolce & Gabbana',
 'Jordan Brand',
 'Giuseppe Zanotti',
 'Churchs',
 'Hermes',
 'Cazal',
 'Marni',
 'Alexandre Plokhov',
 'R.M. Williams',
 'Ron Herman',
 'Sheepskin Coat',
 'Adieu Paris',
 'Eric Emanuel',
 'Mykita',
 'Stone Island',
 'Balmain',
 'Nemen',
 'Nordstrom',
 'Golden Bear',
 'Medicom Toy',
 'Miu Miu',
 'Mister Freedom',
 'Golden Goose',
 '4x1111',
 'Mastermind Japan',
 'Obscur',
 'Warren Lotas',
 'Heliot Emil',
 'Herno',
 'MCM',
 'Chanel',
 'Off-White',
 'Needles',
 'Givenchy',
 'Napapijri',
 'Camiel Fortgens',
 'GmbH',
 'Common Projects',
 'Alexander McQueen',
 'Dries Van Noten',
 'Rhude',
 'Carmina',
 'Pyer Moss',
 'Prada',
 'Aleksandr Manamis',
 'Marsell',
 'Marine Serre',
 'Lemaire',
 'And Wander',
 'Parajumpers',
 'Nine Lives',
 'Avirex',
 'Paraboot',
 'Song For The Mute',
 'Ojardorf',
 'Gucci',
 'Dr. Martens',
 'Lucchese',
 'Loro Piana',
 '10k Solid Gold',
 '11 By Boris Bidjan Saberi',
 'Junya Watanabe',
 'Parts Of Four',
 'Sacai',
 'Maison Margiela',
 'Marcel Everette',
 'Martine Rose',
 'Casey Casey',
 'Casablanca',
 'Oree New York',
 'Raf Simons',
 'Calvin Klein 205W39NYC',
 '10sei0otto',
 '20471120',
 'Aly',
 'ROA',
 'Hender Scheme',
 'Label Under Construction',
 'Palm Angels',
 'Kaws',
 'Julius',
 'Louis Vuitton',
 'Kuboraum',
 'Loewe',
 'Vivienne Westwood',
 'Alden',
 'B.B. Simon',
 'Ann Demeulemeester',
 'Matthew Williamson',
 'George Co',
 'Medicom Bearbrick',
 'Moncler',
 'Mackintosh',
 '1017 ALYX 9SM',
 'Good Art',
 'Miharayasuhiro',
 'Boris Bidjan Saberi',
 'From The First',
 'Haider Ackermann',
 'Thom Browne',
 'Namacheko',
 'Alyx',
 'Dior',
 'Private White V.C.',
 'Schott',
 'Peaceminusone',
 'Visvim',
 '99%Is',
 "Arc'Teryx Veilance",
 'Fugazi',
 'Moncler Gamme Bleu',
 'Saint Laurent Paris',
 'Balenciaga',
 'Rick Owens',
 'Gallery Dept.',
 'Cartier',
 'Carpe Diem',
 'Celine',
 'Chrome Hearts',
 'Canada Goose',
 'Geoffrey B. Small',
 'Rick Owens Drkshdw',
 'Ma+',
 'READYMADE',
 'Archivio J.M. Ribot',
 'Greg Lauren',
 'A Diciannoveventitre',
 'Post Archive Faction',
 'Christian Louboutin',
 'Leon Emanuel Blanck',
 'Mackage',
 'Moose Knuckles',
 'Amiri',
 'Acronym',
 'Layer-0',
 'Carol Christian Poell',
 'A1923',
 'Paul Harnden Shoemakers',
 'Rimowa',
 'Guidi']
    top = [55, 85, 145, 174.0]
    bottoms = [65, 105, 170, 204.0]
    accessories = [55, 88, 150, 180.0]
    footwear = [117, 190, 330, 396.0]
    outerwear = [90, 150, 280, 336.0]
    tailoring = [100, 183, 300, 360.0]




    if input_variables['category_group_top'].values == 1:
        if input_variables['designer'].values in brand_3:
            input_variables['product_class'] = top[3]
            input_variables['brand_value'] = 3
        elif input_variables['designer'].values in brand_2:
            input_variables['product_class'] = top[2]
            input_variables['brand_value'] = 2
        elif input_variables['designer'].values in brand_1:
            input_variables['product_class'] = top[1]
            input_variables['brand_value'] = 1
        elif input_variables['designer'].values in brand_0:
            input_variables['product_class'] = top[0]
            input_variables['brand_value'] = 0


    elif input_variables['category_group_bottoms'].values == 1:
        if input_variables['designer'].values in brand_3:
            input_variables['product_class'] = bottoms[3]
            input_variables['brand_value'] = 3
        elif input_variables['designer'].values in brand_2:
            input_variables['product_class'] = bottoms[2]
            input_variables['brand_value'] = 2
        elif input_variables['designer'].values in brand_1:
            input_variables['product_class'] = bottoms[1]
            input_variables['brand_value'] = 1
        elif input_variables['designer'].values in brand_0:
            input_variables['product_class'] = bottoms[0]
            input_variables['brand_value'] = 0

    elif input_variables['category_group_footwear'].values == 1:
        if input_variables['designer'].values in brand_3:
            input_variables['product_class'] = footwear[3]
            input_variables['brand_value'] = 3
        elif input_variables['designer'].values in brand_2:
            input_variables['product_class'] = footwear[2]
            input_variables['brand_value'] = 2
        elif input_variables['designer'].values in brand_1:
            input_variables['product_class'] = footwear[1]
            input_variables['brand_value'] = 1
        elif input_variables['designer'].values in brand_0:
            input_variables['product_class'] = footwear[0]
            input_variables['brand_value'] = 0

    elif input_variables['category_group_outerwear'].values == 1:
        if input_variables['designer'].values in brand_3:
            input_variables['product_class'] = outerwear[3]
            input_variables['brand_value'] = 3
        elif input_variables['designer'].values in brand_2:
            input_variables['product_class'] = outerwear[2]
            input_variables['brand_value'] = 2
        elif input_variables['designer'].values in brand_1:
            input_variables['product_class'] = outerwear[1]
            input_variables['brand_value'] = 1
        elif input_variables['designer'].values in brand_0:
            input_variables['product_class'] = outerwear[0]
            input_variables['brand_value'] = 0

    elif input_variables['category_group_tailoring'].values == 1:
        if input_variables['designer'].values in brand_3:
            input_variables['product_class'] = tailoring[3]
            input_variables['brand_value'] = 3
        elif input_variables['designer'].values in brand_2:
            input_variables['product_class'] = tailoring[2]
            input_variables['brand_value'] = 2
        elif input_variables['designer'].values in brand_1:
            input_variables['product_class'] = tailoring[1]
            input_variables['brand_value'] = 1
        elif input_variables['designer'].values in brand_0:
            input_variables['product_class'] = tailoring[0]
            input_variables['brand_value'] = 0

    else:
        if input_variables['designer'].values in brand_3:
            input_variables['product_class'] = accessories[3]
            input_variables['brand_value'] = 3
        elif input_variables['designer'].values in brand_2:
            input_variables['product_class'] = accessories[2]
            input_variables['brand_value'] = 2
        elif input_variables['designer'].values in brand_1:
            input_variables['product_class'] = accessories[1]
            input_variables['brand_value'] = 1
        elif input_variables['designer'].values in brand_0:
            input_variables['product_class'] = accessories[0]
            input_variables['brand_value'] = 0

    input_variables.drop(columns = ['designer', 'size', 'category_group'], inplace = True)

    prediction = model.predict(input_variables)[0]
    return flask.render_template('main.html',
                                     original_input={'designer':designer,
                                                     'size':size,
                                                     'category':category,
                                                     'image_count':image_count,
                                                     'feedback_count':feedback_count,
                                                     'condition': condition},
                                     result='$'+str(round(prediction)),
                                     )



# In[ ]:





# In[38]:





# In[39]:





# In[40]:





# In[41]:





# In[42]:





# In[ ]:





# In[43]:





# In[44]:





# In[46]:





# In[47]:





# In[48]:





# In[49]:





# In[50]:





# In[51]:





# In[ ]:





# In[ ]:





# In[52]:





# In[53]:





# In[54]:





# In[55]:





# In[56]:





# In[57]:





# In[58]:





# In[ ]:





# In[65]:





# In[66]:





# In[ ]:





# In[ ]:





# In[67]:





# In[ ]:





# In[68]:





# In[69]:





# In[ ]:





# In[ ]:





# In[ ]:





# In[35]:





# In[37]:





# In[39]:





# In[ ]:
